[package]
name = "college-final-project-sghss"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.81"
diesel = { version = "2.2.1", features = ["postgres", "r2d2"] }
r2d2 = "0.8.10"
serde = { version = "1.0.204", features = ["derive"] }
